;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; # 2
;; Each new term in the Fibonacci sequence is generated by adding the previous
;; two terms. By starting with 1 and 2, the first 10 terms will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun fib (l max)
  (let ((r (reverse l)))
  (if (> (car r) max)
      l
      (fib
       (append
        l
        (list (+ (car r)
           (cadr r)))) max))))

(defun sum-even-fibs (max)
  (reduce '+ (remove-if #'oddp (fib '(0 1) max))))

#+nil
(sum-even-fibs 4000000)


